name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the 'main' branch

jobs:
  build_site:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify your Node.js version
          cache: 'npm'        # Enables caching for npm dependencies

      # 3. Install dependencies using npm ci
      - name: Install Dependencies
        run: npm ci

      # 4. Build the Svelte app
      - name: Build Application
        env:
          BASE_PATH: ''  # Ensures the app is built for the root path
        run: npm run build

      # 5. Upload the build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'  # Path to your build directory

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write         # Grants permission to deploy to GitHub Pages
      id-token: write      # Required for authentication

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
